import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";
import Header from "@/components/shared/header";
import { ToastProvider } from "@/components/providers/toaster-provider";

const nunito = Nunito({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Olx clone App",
  description: "Generated by zd",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased bg-slate-700`}>
        <Header />
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
